### ISSUE TITLE
Sometimes the placed rectangle is upside down

### ISSUE THREAD

**Issue by yeldarby** [mludowise/ARKitRectangleDetection#4]
You can't tell in the code with the white squares since they're symmetrical but I've noticed when adapting this code that sometimes it gets placed upside down relative to the viewer. You can easily notice if you put text in the SceneKit node, for example.

Haven't been able to pin down exactly when this happens. I think it has to do with where you are relative to the ARKit world's origin when the node is placed into the world.

**Comment by mludowise** [comment]
Do you have a screenshot?

My suspicion is it might happen when the phone is in the process of flipping its orientation. `UIView. convertFromCamera(point)` uses the phone's current orientation. However, if the phone was in one orientation when you tapped on the scene and then changed orientations by the time `sceneView.hitTest()` returns, then it will convert the points incorrectly.

**Comment by mludowise** [comment]
At the time I wrote this, I didn't realize that you could pass the image orientation to the [VNImageRequestHandler initializer](https://developer.apple.com/documentation/vision/vnimagerequesthandler/2880303-init) so it will results will already be oriented to the camera.

If my suspicion about what's causing the issue is correct, then using this initializer would be the best fix going forward.

**Comment by yeldarby** [comment]
It doesn't seem to have any correlation with device orientation; I have it locked to portrait mode only. It seems to happen at random (which it probably isn't.. I just haven't been able to deduce the true cause yet). I'll see if I can grab a screen recording to show you what I'm seeing.

**Comment by yeldarby** [comment]
Here are 2 videos (one of it orienting correctly and one upside down). Sorry that they're from 2 different devices; I don't have my iPhone with me today so I grabbed a recording from an iPad to show the upside down issue.

https://www.dropbox.com/sh/90agymxikazz2bh/AADvFsikQ3pGc05zqIrJO0mJa?dl=0

**Comment by mludowise** [comment]
Thanks for the video. Because the size of the AR rectangle is also incorrect, it looks like Vision might be detecting the wrong rectangle from the image.

Have you tried drawing an outline on the view of what the rectangle detection thinks is the correct rectangle to debug? This will tell you if the problem is in rectangle detection or in the conversion from 2D points to 3D points. 

Additionally, I would add some debug statements to `PlaneRectangle.getCorners()`
to see which combination of corners it's using to place the rectangle. It's possible that the only time it doesn't work is with a specific set of 3 corners.

**Comment by yeldarby** [comment]
Cool thanks for the pointers! I'll see what I can figure out and report back if I can get it fixed.

**Comment by mludowise** [comment]
@yeldarby Did you ever figure out what was wrong?

**Comment by yeldarby** [comment]
Haven't had a chance to work on this project in a while. Hoping to get back at it next week

**Comment by yeldarby** [comment]
Sorry I don't have any more underlying info about this bug but I can share how I fixed it in my case (just based on heuristics; not math behind this)

If the orientation is greater than 0 I add `Float.pi` to it. It seemed to work properly when orientation was negative and not when positive.

I can reliably reproduce this by facing away from the table when I start the app then turn around towards what I'm detecting. If it's on the opposite side of the origin from normal then that's when it ends up upside down (it ends up facing the way the phone was facing when it started and setup the coordinate system).

**Comment by ghost** [comment]
I facing the same issue is the solution for this issue.
